#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import bs4 as bs
import requests

source = requests.get('https://www.fool.com/investing/2017/11/21/the-30-dow-jones-stocks.aspx')
soup = bs.BeautifulSoup(source.text, 'lxml')

table = soup.find('table')
    
for company in table.find_all('a'):
    companies = company.text
    print(companies)


        
        
    



